---
- name: Firewalld Open PostgreSQL ports
  ansible.posix.firewalld:
    service: postgresql
    permanent: yes
    immediate: yes
    state: enabled
  when:
    - ansible_facts.services['firewalld.service'].state == "running"